- .gitmodules
- impl/line_iterator.c
This needs to happen in order for it to be integrated into cactus.  
Also, you should use this sonLib all the time (or at least keep yours synced). 
Also, to avoid a similar situation with taf, I'd suggest moving this repo to ComparativeGenomicsToolkit.  The "benedictpaten" url will remain valid (and can be used on git command line) I think forever.  Everything will just redirect automatically to ComparativeGenomicsToolkit.  To do this, you go to "Settings" in this rep, scroll down to the "danger zone" then "transfer ownership".
> switch to the sonLib in comparativeGenomicsToolkit

- taf_index.c
- taffy/impl/tai.c
From 100kb to 10kb.  
I ran a test to pull 4552 conserved elements from a 447-way alignment on EBS (these results will surely vary quite a bit with different disk speeds).  These are stats for the wall times of the 4552 calls to `taffy view`
```
interval               min(s)  max(s)   mean(s)  .tai size(b)
10000                  0.32    1.37     0.557465   6,063,872
10000(gzipped)         0.35    1.40     0.58652    2,354,266
50000                  0.06    4.11     1.07682    1,269,988
100000                 0.03    8.85     2.13459    668,210
```
The 10kb has what looks like a 0.3s loading time plus a worst-case scanning time of 1s.  As expected, longer intervals decrease the former at the expense of the latter.  Zipping the index didn't really change much but was slightly slower. 
I'll …
> Reduce default index interval size

- Makefile
- taf_add_gap_bases.cpp
- taf_index.c
- taf_norm.c
- taf_stats.c
- taf_view.c
- taffy/impl/taf.c
- taffy/impl/tai.c
- taffy/inc/taf.h
- taffy/inc/tai.h
- taffy_main.cpp
- tests/tai/test_tai.py
Right now, all it does is print the (reference) sequence lengths using the TAF index.  
Would like to eventually add basic stuff like
* coverage
* block size
etc.  And I think a lot of this can be done (somewhat) quickly using the index by parallelizing across the file.
> Add taffy stats command

- README.md
- taf_index.c
- taf_stats.c
- taf_view.c
- taffy/_taffy_build.py
- taffy/impl/tai.c
- taffy/inc/tai.h
- taffy/lib.py
- tests/taffyTest.py
- tests/tai/test_tai.py
Can now make a ".tai" index for MAF files too.  Works exactly as for TAF (though I haven't benchmarked much). Has the same requirement that input must be ordered along reference genome. 
Nice error messages on invalid (ie unsorted input) still a todo for both maf and taf. 
The interface should be completely transparent, except `tai_load()` now needs a flag telling whether it's maf or taf. 
`taf view` and `taf stats` can now be used in the exact same manner on either type of file.
> Support MAF indexing

- taffy/impl/taf.c
htslib is required to gzipped or bgzipped input.  But not having it leads to a generic error message about not being able to parse the header.  This fixes that by adding an explicit check for the case of gzipped input with no htslib support.
> Better error msg when opening gzipped input without htslib

- tests/tai/test_tai.py
This fixes issue (which just came up again on cactus's gitlab) where this test was obfuscating upstream errors (in this case a lack of bgzip) by exiting with an unrelated assertion.
> improve stats tests error messaging

- include.mk
This lets someone (ie cactus release scripts) bypass the `pkg-config` htslib setup by setting their own `HTS_CFLAGS` and `HTS_LIB`
> Allow htslib flags pass-through

- include.mk
by automatically setting the use_htslib flag
> Make hts flags overriding a little simpler

- taf_norm.c
- taffy/impl/merge_adjacent_alignments.c
`taffy norm -d` greedily filters out rows corresponding to duplications that would, if left in, prevent blocks from getting merged.  It seemed to work okay on chr22 from a big alignment, but crashed when I tried whole-genome.  This PR fixes a few things, which gets it working on the problem region I'd extracted when it first failed
> Fix up dupe filter in taffy norm

- taf_add_gap_bases.cpp
- taf_index.c
- taf_norm.c
- taf_stats.c
- taf_view.c
- taffy/impl/taf.c
- taffy/inc/taf.h
- tests/tai/evolverMammals_ancestor_name_map.tsv
- tests/tai/evolverMammals_ancestor_rev_name_map.tsv
- tests/tai/test_tai.py
This is the equivalent of `halRenameGenomes` but for MAF/TAF.  
You pass the 2-column TSV to `taffy view` via the new `-n` option, and it will rename the contig names in the alingment block accordingly.  
`.` characters get special treatment consistent with an `<assembly>.<contig>` naming scheme.  
So if the mapping has `hg38 -> Homo_sapiens` then `hg38.chr1` would get renamed to `Homo_sapiens.chr1` etc.  The naming also applies to input regions via the `taffy view -r` option.  So if the MAF/TAF is indexed along hg38, then you can search for `Homo_sapiens.chr1:10-100` via the name map.  
The goal for this is to make working with TAF/MAF files that use accessions for assembly names .
Since both the assembly and contig names can have "."s in them, it uses a a greedy resolver, scanning dots …
> Add support for on-the-fly genome renaming via input tsv to taffy view

- taffy/impl/tai.c
Just noticed that `.tai` region queries were not working correctly on reference chromosomes that are only partially represented in the alignment.  This is a case that now happens when, say, hardmasked gaps are filtered out of the MAF before indexing.
> Fix tai index lookup bug for incomplete chroms

- taf_norm.c
This is a nasty one that came up in  https://github.com/ComparativeGenomicsToolkit/cactus/issues/1201
`taffy norm -d` greedily selects paralogous rows to remove in order to tackle block fragmentation.  Selected rows are deleted and the links are cut between them and their left and right neighbours.  But it looks like I left `left_gap_sequence` field alone on the right neighbour.  This situation (left_gap_sequence but not left link) apparently left following code in a state where it would mis-assign the length field to the merged block.  
This can happen any time `taffy add-gap-bases` and `taffy norm -d` are used in conjunction.  
The patch here is just to remove the gap sequence along with the link to the previous row.  Unfortunately, it calls into question the validity of MAFs previously …
> Fix bug in greedy dupe filter

- .gitmodules
- Makefile
- include.mk
- taf_norm.c
- taffy/_taffy_build.py
- taffy/impl/alignment_block.c
- taffy/impl/merge_adjacent_alignments.c
- taffy/inc/taf.h
- tests/normalize_test.c
This replaces the wfa-based gap sequence aligner with abPOA.  The default cactus scoring parameters are hardcoded in. It passes all tests but I haven't yet tested it at scale.    In particular it will only work to about ~100kb  -- should be fine in practice but at the very least needs an explicit check. 
@benedictpaten do you mind testing it builds and runs for you? 
As an aside, it wouldn't even pass the tests until I sorted the abpoa input by length -- the problem case is below: 
```
printf ">1\nNNNNNNNNNNNNN\n>2\nNNNNNNNNNNNNNNNNNNN\n>3\nNNNNNNNNNNNNNN\n" > x.fa
taffy/submodules/abPOA/bin/abpoa -r 1 -m 0 x.fa
[main] CMD:  taffy/submodules/abPOA/bin/abpoa -r 1 -m 0 x.fa
>1
NNNNNNNNNNNNN-------
>2
NNNNNNNNNNNNN-NNNNNN
>3
NNNNNNNNNNNNNN------
[abpoa_main] Real time: 0.001 sec; CPU: 0.005 …
```
> Use abPOA for gap alignments

- include.mk
I'm copying this directly from Cactus's `include.mk` so that taffy will use the same toggle to switch abpoa between sse2 and avx2.  This is required to integrate taffy [into cactus](https://github.com/ComparativeGenomicsToolkit/cactus/pull/1285), and even for Cactus's [CI tests to run](https://ucsc-ci.com/comparativegenomicstoolkit/cactus/-/pipelines/6292).
> add CACTUS_LEGACY_ARCH toggle to disable avx2

- taffy/impl/tai.c
For example if the indexed file starts with 
```
a
s	hg38.chr1	10000	5	+	248956422	taacc
s	Anc6.Anc6refChr397	0	5	+	17989721	taacc
s	hs1.chr11	1509	5	+	135127769	taacc
```
and you query `taffy view -r hg38.chr1` then you get
```
Region hg38.chr1:0-9223372036854775807 not found in taffy index
```
This only applies to the very first chromosome in the index and is due to a bug in handling the fact that it doesn't have a previous record.  
Anyway, this PR fixes this case by adding an explicit check against the beginning of the index.
> Fix index query bug where overlaps of first position missed

- taffy/impl/tai.c
Fix assertion error  in `view -r` where destructor complained because deleted row wasn't properly unlinked from its neighbours.
> fix assert error in tai clipping

- taffy/impl/tai.c
Range queries on the tai index require clipping alignment blocks.  There was a bug where the block clipping would adjust the alignment's `column_number` field by the number of clipped bases, but not accounting for gaps.
This never came up before because the only tool using the index was `taffy view`, which ignores `column_number` completely and just prints out the block sequences and coordinates which are correct (and the tests all use `taffy view` too).  
But it leads to a crash when trying to iterate columns with the python API, ex (thanks Konstantinos):
```
taffy view -i taffy/tests/evolverMammals.maf | taffy norm -o evolverMammals_norm.taf
taffy index -i  evolverMammals_norm.taf
```
Then run this python script will fail because `block.column_number()` returns the wrong value
``` …
```
> Fix bug where tai index query could return block with incorrect column_number

- taf_sort.c
- taffy/impl/tai.c
- tests/tai/evolverMammals_400_405.maf
- tests/tai/evolverMammals_410_415.maf
- tests/tai/evolverMammals_subregions.bed
- tests/tai/test_tai.py
Taffy index queries were pretty broken, as @benedictpaten pointed out:
```
./bin/taffy view -i ./tests/evolverMammals.maf -c  > ./tests/evolverMammals.taf.gz
./bin/taffy index -i ./tests/evolverMammals.taf.gz
./bin/taffy view -i ./tests/evolverMammals.taf.gz -r Anc0.Anc0refChr0:400-405
Assertion failed: (strlen(column) == column_length), function get_bases, file taf.c, line 125.
/bin/taffy view -i ./tests/evolverMammals.taf.gz -r Anc0.Anc0refChr0:410-413
Assertion failed: (*row != NULL), function parse_coordinates_and_establish_block, file taf.c, line 68.
```
Everything worked fine when indexing and querying the `.maf`, which is probably why it's taken this long to come up.
Anyway, the problem seems to be that the query function works by:
* scan to first block
* slice first block if …
> Fix index query bug

- taf_view.c
- taffy/impl/tai.c
- taffy/inc/tai.h
This makes two changes:
* `taffy view` exits with error message if a 0-length interval passed in (instead of crashing)
* `tai` API returns empty iterator if input range not found in index (instead of returning `NULL` or, in the case of 0-len, crashing).  `tai_has_next()` can check for empty iterator
> fix invalid region checker to catch 0-length interval

- taffy/impl/tai.c
I think the tai index predates taf tags, which would explain the assertion error when the input has a` @`.  Anyway, this little patch should fix it.  Will add a test in the maf quality branch before merging that (as it's really easy to reproduce with qualities).
> fix tai to expect (and ignore) tag characters

- taf_add_gap_bases.cpp
- taf_annotate.c
- taf_norm.c
- taf_sort.c
This PR makes sure that `taffy norm, add-gap-bases, sort` and `annotate` all have 
```
-s --repeatCoordinatesEveryNColumns : Repeat coordinates of each sequence at least every n columns. By default: 10000
-c --useCompression : Write the output using bgzip compression.
```
The `-s` option is particularly important as without it, `taffy index` does not work very well (you can end up with just one record / contig).
> make sure taf-writing tools all have -sc

- README.md
- taf_stats.c
- taffy/inc/tai.h
@benedictpaten Unfortunately this *isn't* the functionality you wanted in that it does not use the index, rather it requires a scan of the whole file.  
So you have the choice of 
* `taffy stats -s` : use the index to quickly get list of reference contig names and their (estimated) lengths
* `taffy stats -b` : print out a bed of all reference intervals (but requires a full scan).  
Putting the intervals themselves in the index requires a fairly major refactor (more than I'd initially thought)-- certainly possible, but not something I want to tackle this week if I can avoid it.
> Option to print BED intervals of reference covered by TAF

- taf_stats.c
- taf_view.c
- taffy/impl/tai.c
`taffy view -r` needs an indexed input file to work.  but if the input is stdin, it just crashes when trying to determine the index filename (#62).  
This PR changes the crash into an error message (ditto `taffy coverage -s`).
> error handling when index needed but input stdin
